FROM debian

# Install dependencies
RUN cd ~
RUN apt-get update
RUN apt-get install -y git python3-pip pkg-config wget usbutils curl

#RUN echo "deb https://packages.cloud.google.com/apt coral-edgetpu-stable main" | tee /etc/apt/sources.list.d/coral-edgetpu.list
RUN echo "deb https://packages.cloud.google.com/apt coral-edgetpu-stable main" | tee /etc/apt/sources.list.d/coral-edgetpu.list
RUN curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add -

RUN apt-get update
RUN apt-get install -y --allow-unauthenticated libedgetpu1-std 

RUN apt-get install -y build-essential libssl-dev zlib1g-dev \
libbz2-dev libreadline-dev libsqlite3-dev curl git \
libncursesw5-dev xz-utils tk-dev libxml2-dev libxmlsec1-dev libffi-dev liblzma-dev \
libhdf5-dev net-tools vim

# Install pyenv and set up environment
RUN curl https://pyenv.run | bash && \
    echo 'export PATH="$HOME/.pyenv/bin:$PATH"' >> ~/.bashrc && \
    echo 'eval "$(pyenv init --path)"' >> ~/.bashrc && \
    echo 'eval "$(pyenv init -)"' >> ~/.bashrc && \
    echo 'eval "$(pyenv virtualenv-init -)"' >> ~/.bashrc && \
    export PATH="$HOME/.pyenv/bin:$PATH" && \
    eval "$(pyenv init --path)" && \
    eval "$(pyenv init -)" && \
    eval "$(pyenv virtualenv-init -)" && \
    pyenv install 3.9.0 && \
    pyenv global 3.9.0

#Install dependencies using pip from the pyenv environment
#RUN apt-get install -y python3-pycoral python3-tflite-runtime	
RUN ~/.pyenv/shims/pip install --upgrade pip
RUN ~/.pyenv/shims/pip install --extra-index-url https://google-coral.github.io/py-repo/ pycoral~=2.0


# Copy requirements file and install dependencies
COPY requirements.txt .

RUN  ~/.pyenv/shims/pip install -r requirements.txt

# Set up working directory
WORKDIR /app

# Copy the rest of the application
COPY backend.py .

# Expose the port the app runs on
EXPOSE 8000

# Command to run the application
CMD ["/bin/bash", "-c", "source ~/.bashrc && exec uvicorn main:app"]
